### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by immattdavison** [Abhay557/Code-Editor#3]
Currently if viewed on a small screen the site is not fully responsive, this should be edited using media queries in the CSS to make sure that the input and iframe both have the correct amount of space throughout all screen sizes.

**Comment by nikolaischunk** [comment]
I reccomend using bootstrap. looks way cleaner and is automatically responsive. ;)

**Comment by immattdavison** [comment]
> I reccomend using bootstrap. looks way cleaner and is automatically responsive. ;)

I agree with this completely, Bootstrap will allow for a much easier experience for both the author and users and will make the site clean and easy to use!

**Comment by immattdavison** [comment]
Sorted - [View Commit](https://github.com/Abhay557/Code-Editor/commit/eabfb4bfed4fa89c72c0db4e402802fc3c903209)
